export const USER_SIGNIN = "USER_SIGNIN";
export const USER_SET_IS_LOADING = "USER_SET_IS_LOADING";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_CHANGE_PASSWORD = "USER_CHANGE_PASSWORD";
